language: python
#sudo: false
#virtualenv:
#  system_site_packages: true
python:
  - "3.5"
#env:
#  - DJANGO="Django>=1.11.0,<1.12.0"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8
before_script:
  - "flake8 --max-complexity=7"
# command to run tests
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
#  - pytest # or py.test for Python versions 3.5 and below
