x-pod-volumes: &pod-volumes
  - .:/usr/src/app

x-elasticsearch-volumes: &elasticsearch-volumes
  - ./dockerfile-dev-with-volumes/config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

version: '3.7'

services:
  pod:
    container_name: pod-dev-with-volumes
    build:
      context: .
      dockerfile: dockerfile-dev-with-volumes/pod/Dockerfile
      args:
        NODE_VERSION: "node:19"
        PYTHON_VERSION: "python:3.7-buster"
    depends_on:
      - elasticsearch
      - redis
    env_file:
      - ./.env.dev
    ports:
      - 9090:8080
    volumes: *pod-volumes

  elasticsearch:
    container_name: elasticsearch-with-volumes
    build:
      context: .
      dockerfile: dockerfile-dev-with-volumes/elasticsearch/dockerfile-elasticsearch-dev
      args:
#        ELASTICSEARCH_VERSION: "elasticsearch:6.8.23"
        ELASTICSEARCH_VERSION: "elasticsearch:7.17.7"
    env_file:
      - ./.env.dev
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes: *elasticsearch-volumes

  redis:
    container_name: redis-with-volumes
    image: redis:alpine3.16
# TODO
#    image: harbor.urba.univ-lille.fr/store/redis:alpine3.16
    ports:
      - 6379:6379