name: Black

on:
  workflow_run:
    workflows:
      - "Prettier"
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Black formatting code
        run: black . -l 80
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Eliam LOTONGA'
          git config --global user.email 'e.m.lotonga@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Fixup: format code with Black"
